name: My First Workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "Hello, GitHub Actions!"
      - name: print name
        run: echo "hello, srishti here!" 
  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: printt
        run: echo "Goodbye from second job!"
